/**
 * Class PluginProjectbridgeTask
 * Modernized for GLPI 11 and PHP 8.4
 */
class PluginProjectbridgeTask extends CommonDBTM {
    /**
     * @var ProjectTask|null
     */
    private ?ProjectTask $_task = null;

    /**
     * Constructor
     *
     * @param int|null $task_id
     */
    public function __construct(?int $task_id = null) {
        if (!empty($task_id)) {
            $task = new ProjectTask();
            if ($task->getFromDB($task_id)) {
                $this->_task = $task;
            }
        }
    }

    /**
     * Close all open tasks and create excess ticket (GLPI 11 compatible)
     * @param array $tasks
     * @param bool $fromCronTask
     * @return array
     */
    public static function closeTaskAndCreateExcessTicket(array $tasks, bool $fromCronTask = true): array {
        global $DB;
        $newTicketIds = [];
        // Use status 6 for closed if constant not available
        $status_closed = 6;
        if (!class_exists('Ticket')) {
            require_once(GLPI_ROOT . '/inc/ticket.class.php');
        }
        foreach ($tasks as $task_data) {
            $taskId = $task_data['id'] ?? null;
            if (!$taskId) continue;
            $update = [
                'id' => $taskId,
                'status' => $status_closed,
            ];
            $DB->update('glpi_projecttasks', $update, ['id' => $taskId]);
            $ticketFields = [
                'name' => 'Excess Ticket for Task ' . $taskId,
                'status' => $status_closed,
                'content' => 'Auto-generated by ProjectBridge',
            ];
            if (method_exists('Ticket', 'add')) {
                $ticket = new \Ticket();
                $newTicketId = $ticket->add($ticketFields);
            } else {
                // Fallback: direct DB insert
                $DB->insert('glpi_tickets', $ticketFields);
                $newTicketId = $DB->insert_id();
            }
            if ($newTicketId) {
                $newTicketIds[] = $newTicketId;
            }
        }
        return $newTicketIds;
    }

    // ...existing code for other methods (updateProjectTaskProgressPercent, cronUpdateProgressPercent, etc.)...
}
